In [1]:
import numpy as np

# tạo mảng
a = np.array([1,2,3])

#in mảng
print(a)

#in ra 1 phan tu
ele = a[2]
print(ele)

[1 2 3]
3


In [2]:
# tạo mảng 2 chiều
matrix = np.array([[1,2,3],[3,5,4],[2,1,3]])

#in mảng
print(matrix)

#in ra 1 phan tu
ele = matrix[2,2]
print(ele)

[[1 2 3]
 [3 5 4]
 [2 1 3]]
3


In [3]:
# tạo mảng full zero
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
# tạo mảng từ 1 -> 100
a = np.arange(2,100)
print(a)

# tạo mảng cách đều
a = np.arange(2,100,3)
print(a)

# xac dinh kieu du lieu
a = np.ones(5, dtype=np.int64)
print(a)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71
 74 77 80 83 86 89 92 95 98]
[1 1 1 1 1]


In [22]:
# thêm xóa sửa sx mảng

# Tạo mảng ban đầu
arr = np.array([3,6,9,1,3,2,5])
print(arr)

# sx
arr = np.sort(arr)
print(arr)

# sx nguoc
arr = arr[::-1]
print(arr)

#them phan tu vao mang
arr = np.append(arr, 7)
print(arr)

#xoa phan tu trong mang
arr = np.delete(arr,3)
print(arr)



[3 6 9 1 3 2 5]
[1 2 3 3 5 6 9]
[9 6 5 3 3 2 1]
[9 6 5 3 3 2 1 7]
[9 6 5 3 2 1 7]


In [40]:
# tao 1 mang 2 chieu
matrix = np.array([[1,2,3],[3,5,4],[2,1,3],[4,2,3],[1,5,4],[6,1,3]])
print(matrix)

#sap xep theo hang
matrix = np.sort(matrix, axis = 1) #tang dan 
print(matrix)

#sap xep theo cot
matrix = -np.sort(-matrix, axis = 0) # giam dan, thêm - trước matrix và np
print(matrix)

[[1 2 3]
 [3 5 4]
 [2 1 3]
 [4 2 3]
 [1 5 4]
 [6 1 3]]
[[1 2 3]
 [3 4 5]
 [1 2 3]
 [2 3 4]
 [1 4 5]
 [1 3 6]]
[[3 4 6]
 [2 4 5]
 [1 3 5]
 [1 3 4]
 [1 2 3]
 [1 2 3]]
